---
name: Setup Prolog
author: Yevhen Fabizhevskyi
description: This action sets up Prolog programming language.
branding:
  icon: terminal
  color: gray-dark
inputs:
  force:
    description: |
      If "true" it installs swipl even if it is already installed on a runner.
      Otherwise, skips installation.
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Validate inputs
      id: validate-inputs
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src
    - name: Prepare metadata
      id: metadata
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: |
        to_install="false"
        if [ "${INPUT_FORCE}" = "true" ] || ! command -v swipl >/dev/null 2>&1; then
          to_install="true"
        fi
        echo "to-install=${to_install}" >> "$GITHUB_OUTPUT"
        echo "os=$(echo "${RUNNER_OS}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Install swipl
      if: ${{ steps.metadata.outputs.to-install == 'true' }}
      run: ./install-swipl-${{ steps.metadata.outputs.os }}.sh
      shell: sh
      working-directory: ${{ github.action_path }}/src
    - name: Print version
      run: swipl --version
      shell: sh
